### ISSUE TITLE
ImportError: cannot import name PipSession

### ISSUE THREAD

**Issue by jmaclabs** [pipermerriam/flex#74]
Excited to try out flex but it's failing on the `pip install flex` with ImportError: cannot import name PipSession

I attempted to install while in an active virtualenvs. When I deactivated, it worked.

full pip.log:
```python
-----------------------------------------------------------
/Users/jmac/.virtualenvs/test/bin/pip run on Fri Apr 17 18:26:11 2015
Downloading/unpacking flex

  Getting page https://pypi.python.org/simple/flex/
  URLs to search for versions for flex:
  * https://pypi.python.org/simple/flex/
  Analyzing links from page https://pypi.python.org/simple/flex/
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-2.1.0-py2-none-any.whl#md5=96236f480e1275a49ba9c5722436eaf1 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-2.2.0-py2-none-any.whl#md5=06e87bb689e08d0ca05a3a65fc6dfd92 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-2.3.0-py2-none-any.whl#md5=0cacdc8e292edce2b88848a3f8ac20d1 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-2.4.0-py2-none-any.whl#md5=9e1bfc45eef93e5709cce185ae7fcdb7 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-2.5.0-py2-none-any.whl#md5=6f5ad0400661857795fe3b346c8cc330 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-2.6.0-py2-none-any.whl#md5=07a3ac34578d68d6dbfd427fe0a8a2fe (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-2.7.0-py2-none-any.whl#md5=91d8817890ed6f3a99f47b28573eaef1 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-2.8.0-py2-none-any.whl#md5=20d4f475b3acce2e7275f60a82d116fe (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-3.0.0-py2-none-any.whl#md5=b5c2edbd7be990094dae4cc1484f2929 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-3.1.0-py2-none-any.whl#md5=e2ddbdeea959a0749a6c7ac90b3ea35f (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-3.2.0-py2-none-any.whl#md5=3d31251d2afdfae4f966d779dcf4b4c7 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-3.3.0-py2-none-any.whl#md5=b3f2c604a7b4f4589a36d48bb2d63e6d (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-3.4.0-py2-none-any.whl#md5=cc79fec9685c985af5218fb64ed7052d (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-3.4.1-py2-none-any.whl#md5=ab53845d2ac011598b8b7dcba429cf45 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-3.5.0-py2-none-any.whl#md5=5c7ca5489714e68a071afe2a2ca6caf5 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-3.5.1-py2-none-any.whl#md5=ceba56bd41f8dc152cb89b1197957d93 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/f/flex/flex-4.0.0-py2-none-any.whl#md5=2053d494350eff51530c11dade68b4b3 (from https://pypi.python.org/simple/flex/); unknown archive format: .whl
    Found link https://pypi.python.org/packages/any/f/flex/flex-2.1.0.macosx-10.10-x86_64.tar.gz#md5=acf62f066411583b0e1df4ab7e98e692 (from https://pypi.python.org/simple/flex/), version: 2.1.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-2.2.0.macosx-10.10-x86_64.tar.gz#md5=6e28c39eb689fbed209cd6ff0161466a (from https://pypi.python.org/simple/flex/), version: 2.2.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-2.3.0.macosx-10.10-x86_64.tar.gz#md5=2560721ec8a7101206bec2a02e8c1328 (from https://pypi.python.org/simple/flex/), version: 2.3.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-2.4.0.macosx-10.10-x86_64.tar.gz#md5=a2b14268022ba352c46cb0fc3f6ce609 (from https://pypi.python.org/simple/flex/), version: 2.4.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-2.5.0.macosx-10.10-x86_64.tar.gz#md5=49e95273d23a8c83bf2b6060a11bfe0d (from https://pypi.python.org/simple/flex/), version: 2.5.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-2.6.0.macosx-10.10-x86_64.tar.gz#md5=cbd8a7b5a71d6274ff70d5e1683c382f (from https://pypi.python.org/simple/flex/), version: 2.6.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-2.7.0.macosx-10.10-x86_64.tar.gz#md5=13cb539d02c1043453ac9fbea606ccbe (from https://pypi.python.org/simple/flex/), version: 2.7.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-2.8.0.macosx-10.10-x86_64.tar.gz#md5=d8d3f2ef2c71a8de8347f96e37fdce9d (from https://pypi.python.org/simple/flex/), version: 2.8.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-3.0.0.macosx-10.10-x86_64.tar.gz#md5=6631a3f76049a0b22992f1b11dc99f59 (from https://pypi.python.org/simple/flex/), version: 3.0.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-3.1.0.macosx-10.10-x86_64.tar.gz#md5=7539da3bccd62093be1b096094f7fc44 (from https://pypi.python.org/simple/flex/), version: 3.1.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-3.2.0.macosx-10.10-x86_64.tar.gz#md5=9e59c628faaecbbf93f62cb3d85dd46b (from https://pypi.python.org/simple/flex/), version: 3.2.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-3.3.0.macosx-10.10-x86_64.tar.gz#md5=52fe0f56aa3b3a13fe83f687474d4a99 (from https://pypi.python.org/simple/flex/), version: 3.3.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-3.4.0.macosx-10.10-x86_64.tar.gz#md5=9a91c29cfd6999f35af588b6714c6bdd (from https://pypi.python.org/simple/flex/), version: 3.4.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-3.4.1.macosx-10.10-x86_64.tar.gz#md5=9a0ae5b77f7fece64a3a6635872a5bd0 (from https://pypi.python.org/simple/flex/), version: 3.4.1.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-3.5.0.macosx-10.10-x86_64.tar.gz#md5=a1156524b44be68627d0e0e8cdd4efee (from https://pypi.python.org/simple/flex/), version: 3.5.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-3.5.1.macosx-10.10-x86_64.tar.gz#md5=cb4bad77109acd19bd4649289f99d697 (from https://pypi.python.org/simple/flex/), version: 3.5.1.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/any/f/flex/flex-4.0.0.macosx-10.10-x86_64.tar.gz#md5=e9a8f78e5011594f574affd2cf285c18 (from https://pypi.python.org/simple/flex/), version: 4.0.0.macosx-10.10-x86_64
    Found link https://pypi.python.org/packages/source/f/flex/flex-1.0.0.tar.gz#md5=1018702e4443d0a7a9d9bd2107310b94 (from https://pypi.python.org/simple/flex/), version: 1.0.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-1.1.0.tar.gz#md5=30495feb0099a178dcdc5e49c51fa425 (from https://pypi.python.org/simple/flex/), version: 1.1.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-1.2.0.tar.gz#md5=d736158d9df43474679114d43058097d (from https://pypi.python.org/simple/flex/), version: 1.2.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-1.3.0.tar.gz#md5=249b7c00dc4245a712d1de580f29ea2c (from https://pypi.python.org/simple/flex/), version: 1.3.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-1.4.0.tar.gz#md5=6b7987bb7099da118c374951a6d53ae7 (from https://pypi.python.org/simple/flex/), version: 1.4.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-1.5.0.tar.gz#md5=9a295ffaf15875c8c132368cee45866f (from https://pypi.python.org/simple/flex/), version: 1.5.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-1.6.0.tar.gz#md5=4526002b71e95a224d6190f38e16edc9 (from https://pypi.python.org/simple/flex/), version: 1.6.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-1.7.0.tar.gz#md5=448391a732d90d2cee4e7c74e2b8fbd0 (from https://pypi.python.org/simple/flex/), version: 1.7.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-1.8.0.tar.gz#md5=e3c3d4fb0a21e2bf64cd0795751bf6a8 (from https://pypi.python.org/simple/flex/), version: 1.8.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-1.9.0.tar.gz#md5=4311508b8b5f08b6ce1e042ee864c44d (from https://pypi.python.org/simple/flex/), version: 1.9.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-2.0.0.tar.gz#md5=f7c529d270cbb4304d6cc8cd04ea5214 (from https://pypi.python.org/simple/flex/), version: 2.0.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-2.1.0.tar.gz#md5=8809a0bbe1627ad80212e0956c2825cc (from https://pypi.python.org/simple/flex/), version: 2.1.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-2.2.0.tar.gz#md5=151661ef30d890445cc0159690fc9545 (from https://pypi.python.org/simple/flex/), version: 2.2.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-2.3.0.tar.gz#md5=73e5614ec8b756a64d975cf565885df3 (from https://pypi.python.org/simple/flex/), version: 2.3.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-2.4.0.tar.gz#md5=78119930f6f66b9c804c1dfe47827d71 (from https://pypi.python.org/simple/flex/), version: 2.4.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-2.5.0.tar.gz#md5=f844ae18856c44eb73533ea2a127f7e6 (from https://pypi.python.org/simple/flex/), version: 2.5.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-2.6.0.tar.gz#md5=79bb821c782226e81bd988bad2e40b15 (from https://pypi.python.org/simple/flex/), version: 2.6.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-2.7.0.tar.gz#md5=c9f344f547974998885011478cbc892e (from https://pypi.python.org/simple/flex/), version: 2.7.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-2.8.0.tar.gz#md5=be62c79489715f00f93686344b5a500e (from https://pypi.python.org/simple/flex/), version: 2.8.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-3.0.0.tar.gz#md5=f6fd7589ad19e62cc5b3664cc2f54509 (from https://pypi.python.org/simple/flex/), version: 3.0.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-3.1.0.tar.gz#md5=9031eefd1079733bb3bd8f7aa84cdaee (from https://pypi.python.org/simple/flex/), version: 3.1.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-3.2.0.tar.gz#md5=169b6c22645f1b5c97cba503ef95cede (from https://pypi.python.org/simple/flex/), version: 3.2.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-3.3.0.tar.gz#md5=ab8cdc7c543e500a7a4347e93ae90aa8 (from https://pypi.python.org/simple/flex/), version: 3.3.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-3.4.0.tar.gz#md5=f568a75e5b92989353585a1a67ec9ac6 (from https://pypi.python.org/simple/flex/), version: 3.4.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-3.4.1.tar.gz#md5=54f1a23de11974853a8166912ec48ceb (from https://pypi.python.org/simple/flex/), version: 3.4.1
    Found link https://pypi.python.org/packages/source/f/flex/flex-3.5.0.tar.gz#md5=b69478a737007bed231a05b249f5e5b1 (from https://pypi.python.org/simple/flex/), version: 3.5.0
    Found link https://pypi.python.org/packages/source/f/flex/flex-3.5.1.tar.gz#md5=dc495484eb7d54c51ab3fa12731583a7 (from https://pypi.python.org/simple/flex/), version: 3.5.1
    Found link https://pypi.python.org/packages/source/f/flex/flex-4.0.0.tar.gz#md5=73aefc1363cc545f61a01e69a8be9d29 (from https://pypi.python.org/simple/flex/), version: 4.0.0
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-2.1.0.macosx-10.10-x86_64.tar.gz#md5=acf62f066411583b0e1df4ab7e98e692 (from https://pypi.python.org/simple/flex/), version 2.1.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-2.2.0.macosx-10.10-x86_64.tar.gz#md5=6e28c39eb689fbed209cd6ff0161466a (from https://pypi.python.org/simple/flex/), version 2.2.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-2.3.0.macosx-10.10-x86_64.tar.gz#md5=2560721ec8a7101206bec2a02e8c1328 (from https://pypi.python.org/simple/flex/), version 2.3.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-2.4.0.macosx-10.10-x86_64.tar.gz#md5=a2b14268022ba352c46cb0fc3f6ce609 (from https://pypi.python.org/simple/flex/), version 2.4.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-2.5.0.macosx-10.10-x86_64.tar.gz#md5=49e95273d23a8c83bf2b6060a11bfe0d (from https://pypi.python.org/simple/flex/), version 2.5.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-2.6.0.macosx-10.10-x86_64.tar.gz#md5=cbd8a7b5a71d6274ff70d5e1683c382f (from https://pypi.python.org/simple/flex/), version 2.6.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-2.7.0.macosx-10.10-x86_64.tar.gz#md5=13cb539d02c1043453ac9fbea606ccbe (from https://pypi.python.org/simple/flex/), version 2.7.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-2.8.0.macosx-10.10-x86_64.tar.gz#md5=d8d3f2ef2c71a8de8347f96e37fdce9d (from https://pypi.python.org/simple/flex/), version 2.8.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-3.0.0.macosx-10.10-x86_64.tar.gz#md5=6631a3f76049a0b22992f1b11dc99f59 (from https://pypi.python.org/simple/flex/), version 3.0.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-3.1.0.macosx-10.10-x86_64.tar.gz#md5=7539da3bccd62093be1b096094f7fc44 (from https://pypi.python.org/simple/flex/), version 3.1.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-3.2.0.macosx-10.10-x86_64.tar.gz#md5=9e59c628faaecbbf93f62cb3d85dd46b (from https://pypi.python.org/simple/flex/), version 3.2.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-3.3.0.macosx-10.10-x86_64.tar.gz#md5=52fe0f56aa3b3a13fe83f687474d4a99 (from https://pypi.python.org/simple/flex/), version 3.3.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-3.4.0.macosx-10.10-x86_64.tar.gz#md5=9a91c29cfd6999f35af588b6714c6bdd (from https://pypi.python.org/simple/flex/), version 3.4.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-3.4.1.macosx-10.10-x86_64.tar.gz#md5=9a0ae5b77f7fece64a3a6635872a5bd0 (from https://pypi.python.org/simple/flex/), version 3.4.1.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-3.5.0.macosx-10.10-x86_64.tar.gz#md5=a1156524b44be68627d0e0e8cdd4efee (from https://pypi.python.org/simple/flex/), version 3.5.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-3.5.1.macosx-10.10-x86_64.tar.gz#md5=cb4bad77109acd19bd4649289f99d697 (from https://pypi.python.org/simple/flex/), version 3.5.1.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/any/f/flex/flex-4.0.0.macosx-10.10-x86_64.tar.gz#md5=e9a8f78e5011594f574affd2cf285c18 (from https://pypi.python.org/simple/flex/), version 4.0.0.macosx-10.10-x86_64 is a pre-release (use --pre to allow).
  Using version 4.0.0 (newest of versions: 4.0.0, 3.5.1, 3.5.0, 3.4.1, 3.4.0, 3.3.0, 3.2.0, 3.1.0, 3.0.0, 2.8.0, 2.7.0, 2.6.0, 2.5.0, 2.4.0, 2.3.0, 2.2.0, 2.1.0, 2.0.0, 1.9.0, 1.8.0, 1.7.0, 1.6.0, 1.5.0, 1.4.0, 1.3.0, 1.2.0, 1.1.0, 1.0.0)
  Downloading flex-4.0.0.tar.gz

  Downloading from URL https://pypi.python.org/packages/source/f/flex/flex-4.0.0.tar.gz#md5=73aefc1363cc545f61a01e69a8be9d29 (from https://pypi.python.org/simple/flex/)
  Running setup.py egg_info for package flex

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/Users/jmac/.virtualenvs/test/build/flex/setup.py", line 4, in <module>

        from pip.download import PipSession

    ImportError: cannot import name PipSession

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/jmac/.virtualenvs/test/build/flex/setup.py", line 4, in <module>

    from pip.download import PipSession

ImportError: cannot import name PipSession

----------------------------------------

Cleaning up...

  Removing temporary dir /Users/jmac/.virtualenvs/test/build...
Command python setup.py egg_info failed with error code 1 in /Users/jmac/.virtualenvs/test/build/flex

Exception information:
Traceback (most recent call last):
  File "/Users/jmac/.virtualenvs/test/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/Users/jmac/.virtualenvs/test/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/jmac/.virtualenvs/test/lib/python2.7/site-packages/pip/req.py", line 1134, in prepare_files
    req_to_install.run_egg_info()
  File "/Users/jmac/.virtualenvs/test/lib/python2.7/site-packages/pip/req.py", line 259, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Users/jmac/.virtualenvs/test/lib/python2.7/site-packages/pip/util.py", line 670, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /Users/jmac/.virtualenvs/test/build/flex
```

**Comment by pipermerriam** [comment]
Can you tell me what version of pip you are using.

**Comment by jmaclabs** [comment]
Hi, sure!  

pip 6.1.1 from /usr/local/lib/python2.7/site-packages (python 2.7)

**Comment by pipermerriam** [comment]
odd,  on a fresh virtualenv I get no problems with `6.1.1`

```bash
$ pip install flex
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Collecting flex
  Downloading flex-4.0.0-py2-none-any.whl (71kB)
    100% |████████████████████████████████| 73kB 110kB/s
Collecting six>=1.7.3 (from flex)
  Downloading six-1.9.0-py2.py3-none-any.whl
Collecting click>=3.3 (from flex)
  Using cached click-4.0-py2.py3-none-any.whl
Collecting PyYAML>=3.11 (from flex)
  Using cached PyYAML-3.11.tar.gz
Collecting iso8601>=0.1.10 (from flex)
  Downloading iso8601-0.1.10.tar.gz
Collecting requests>=2.4.3 (from flex)
  Using cached requests-2.6.0-py2.py3-none-any.whl
Collecting jsonpointer==1.7 (from flex)
  Downloading jsonpointer-1.7-py2-none-any.whl
Collecting rfc3987>=1.3.4 (from flex)
  Downloading rfc3987-1.3.4.tar.gz
Collecting validate-email>=1.2 (from flex)
  Downloading validate_email-1.3.tar.gz
Installing collected packages: six, click, PyYAML, iso8601, requests, jsonpointer, rfc3987, validate-email, flex
  Running setup.py install for PyYAML
  Running setup.py install for iso8601
  Running setup.py install for rfc3987
  Running setup.py install for validate-email
Successfully installed PyYAML-3.11 click-4.0 flex-4.0.0 iso8601-0.1.10 jsonpointer-1.7 requests-2.6.0 rfc3987-1.3.4 six-1.9.0 validate-email-1.3
```

Can you check to see if you have different versions across your virtual envs?

**Comment by pipermerriam** [comment]
@jmaclabs I've just pushed `4.0.1` up to pypi.  I removed the code that was causing you problems.  It's a pattern I've been moving away from and this was enough motivation to go ahead and get rid of it.  Lemme know if you're still having issues.

**Comment by jmaclabs** [comment]
It works!  I tested `pip install --upgrade flex` with my .virtualenvs active and deactivated and both worked.

I also uninstalled and did a clean install using pip.

Awesome response time! Thanks Piper!
